language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install: 
  - sudo apt-get update -y
  - sudo apt-get install -qq libgdal1h
  - sudo apt-get install -qq python-numpy python-scientific
  - sudo apt-get install -qq python-shapely
  - sudo apt-get install -qq python-qt4
  - sudo apt-get install -qq proj
  - sudo apt-get install -qq gmsh
  - sudo apt-get install -qq gmt
  - sudo apt-get install -qq python-gdal
  - sudo apt-get install -qq python-cairo
install:
  - sudo chef/run.sh
script:  python test.py
