language: python
python:
  - "2.7_with_system_site_packages"
  - "3.2_with_system_site_packages"
cache:
  apt: true
before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y -qq libgdal1h proj gmsh gmt
  - sudo apt-get install -y -qq python-numpy python-scientific python-shapely python-qt4 python-gdal
  - sudo apt-get install -y -qq python3-numpy python3-pyqt4 python3-gdal
  - sudo apt-get install -y -qq libffi-dev libcairo2
install:
  - sudo chef/run.sh
  - pip install cairocffi
  - pip install -U .
script:  python test.py
