language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install: 
  - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
  - sudo apt-get remove -y libgdal1
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -y
  - sudo apt-get install -y python-gdal
install:
  - pip install . 'httmock >= 1.2'
script:  python test.py
